# permissions for end users to view clusterscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: basic-k8s-ctrl
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-viewer-role
rules:
- apiGroups:
  - spectrocloud.k8s.arturshadnik
  resources:
  - clusterscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spectrocloud.k8s.arturshadnik
  resources:
  - clusterscans/status
  verbs:
  - get
