apiVersion: scan.arturshadnik.k8s.io/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: basic-k8s-ctrl
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
