apiVersion: scan.arturshadnik.k8s.io/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: basic-k8s-ctrl
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  jobType: "monitoring"
  image: "arturshadnik/example:latest"
  command: ["./run.sh"]
  args: ["--example"]
  schedule: "0 0 * * 1" # run weekly, monday at midnight
  oneOff: false # if true, schedule can be omitted
  scanConfig:
    scanLevel: "deep"
    targetNamespaces: ["default"]
  deadline: 3600 # time limit
  restartPolicy: "OnFailure"
