name: Create Issue


on: 
  issues:
    types: [opened]

concurrency: 
  group: create-issue-${{ github.ref }}
  cancel-in-progress: true

env:
  COLUMN_ID: 1
  LABEL_NAME: test-copy

jobs:
  create-issue:
    if: contains(github.event.issue.labels.*.name, 'test-copy')
    runs-on: ubuntu-latest
    steps:
      - name: Filter labels
        id: filter_labels
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '[.[] | select(.name != "${{ env.LABEL_NAME }}") | .name] | join(",")')
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
      - name: Create Issue
        id: create_issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          owner: arturshadnik
          repo: gsc
          assignees: ${{ join(github.event.issue.assignees.*.login, ',') }}
          labels: ${{ steps.filter_labels.outputs.labels }}
      - name: Get Issue Number
        id: get_issue_number
        run: |
          echo "issue_id=${{ steps.create_issue.outputs.id }}" >> $GITHUB_OUTPUT
      - name: Create Card
        id: create_card
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/projects/columns/${{ env.COLUMN_ID }}/cards \
          -d '{"note":"this is a test payload", "content_type":"Issue", "content_id":${{ steps.get_issue_number.outputs.issue_id }}}'
      - name: Get Card ID
        id: get_card_id
        run: |
          echo "card_id=${{ steps.create_card.outputs.card_id }}" >> $GITHUB_OUTPUT
      # - name: Move Card
      #   id: move_card
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/projects/columns/${{ env.COLUMN_ID }}/cards/${{ steps.get_card_id.outputs.card_id }}/moves